/*
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at https://mozilla.org/MPL/2.0/.
*/

#ifndef ALUTIL_EFX_H
#define ALUTIL_EFX_H

#include <alext.h>

#ifdef ALUTIL_EFX_IMPL
    #define ALUTIL_EFX_EXTERN_KW
#else
    #define ALUTIL_EFX_EXTERN_KW extern
#endif

ALUTIL_EFX_EXTERN_KW LPALGENEFFECTS alGenEffects;
ALUTIL_EFX_EXTERN_KW LPALDELETEEFFECTS alDeleteEffects;
ALUTIL_EFX_EXTERN_KW LPALISEFFECT alIsEffect;
ALUTIL_EFX_EXTERN_KW LPALEFFECTI alEffecti;
ALUTIL_EFX_EXTERN_KW LPALEFFECTIV alEffectiv;
ALUTIL_EFX_EXTERN_KW LPALEFFECTF alEffectf;
ALUTIL_EFX_EXTERN_KW LPALEFFECTFV alEffectfv;
ALUTIL_EFX_EXTERN_KW LPALGETEFFECTI alGetEffecti;
ALUTIL_EFX_EXTERN_KW LPALGETEFFECTI alGetEffectiv;
ALUTIL_EFX_EXTERN_KW LPALGETEFFECTF alGetEffectf;
ALUTIL_EFX_EXTERN_KW LPALGETEFFECTFV alGetEffectfv;

ALUTIL_EFX_EXTERN_KW LPALGENFILTERS alGenFilters;
ALUTIL_EFX_EXTERN_KW LPALDELETEFILTERS alDeleteFilters;
ALUTIL_EFX_EXTERN_KW LPALISFILTER alIsFilter;
ALUTIL_EFX_EXTERN_KW LPALFILTERI alFilteri;
ALUTIL_EFX_EXTERN_KW LPALFILTERIV alFilteriv;
ALUTIL_EFX_EXTERN_KW LPALFILTERF alFilterf;
ALUTIL_EFX_EXTERN_KW LPALFILTERFV alFilterfv;
ALUTIL_EFX_EXTERN_KW LPALGETFILTERI alGetFilteri;
ALUTIL_EFX_EXTERN_KW LPALGETFILTERIV alGetFilteriv;
ALUTIL_EFX_EXTERN_KW LPALGETFILTERF alGetFilterf;
ALUTIL_EFX_EXTERN_KW LPALGETFILTERFV alGetFilterfv;

ALUTIL_EFX_EXTERN_KW LPALGENAUXILIARYEFFECTSLOTS alGenAuxiliaryEffectSlots;
ALUTIL_EFX_EXTERN_KW LPALDELETEAUXILIARYEFFECTSLOTS alDeleteAuxiliaryEffectSlots;
ALUTIL_EFX_EXTERN_KW LPALISAUXILIARYEFFECTSLOT alIsAuxiliaryEffectSlot;
ALUTIL_EFX_EXTERN_KW LPALAUXILIARYEFFECTSLOTI alAuxiliaryEffectSloti;
ALUTIL_EFX_EXTERN_KW LPALAUXILIARYEFFECTSLOTIV alAuxiliaryEffectSlotiv;
ALUTIL_EFX_EXTERN_KW LPALAUXILIARYEFFECTSLOTF alAuxiliaryEffectSlotf;
ALUTIL_EFX_EXTERN_KW LPALAUXILIARYEFFECTSLOTFV alAuxiliaryEffectSlotfv;
ALUTIL_EFX_EXTERN_KW LPALGETAUXILIARYEFFECTSLOTI alGetAuxiliaryEffectSloti;
ALUTIL_EFX_EXTERN_KW LPALGETAUXILIARYEFFECTSLOTIV alGetAuxiliaryEffectSlotiv;
ALUTIL_EFX_EXTERN_KW LPALGETAUXILIARYEFFECTSLOTF alGetAuxiliaryEffectSlotf;
ALUTIL_EFX_EXTERN_KW LPALGETAUXILIARYEFFECTSLOTFV alGetAuxiliaryEffectSlotfv;

#undef ALUTIL_EFX_EXTERN_KW

// returns 0 on success.
char alutil_loadEFX(void);

#endif