/*
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at https://mozilla.org/MPL/2.0/.
*/

#ifndef ALBASE_EFX_H
#define ALBASE_EFX_H

#include <alext.h>

#ifdef ALBASE_EFX_IMPL
    #define ALBASE_EFX_EXTERN_KW
#else
    #define ALBASE_EFX_EXTERN_KW extern
#endif

ALBASE_EFX_EXTERN_KW LPALGENEFFECTS alGenEffects;
ALBASE_EFX_EXTERN_KW LPALDELETEEFFECTS alDeleteEffects;
ALBASE_EFX_EXTERN_KW LPALISEFFECT alIsEffect;
ALBASE_EFX_EXTERN_KW LPALEFFECTI alEffecti;
ALBASE_EFX_EXTERN_KW LPALEFFECTIV alEffectiv;
ALBASE_EFX_EXTERN_KW LPALEFFECTF alEffectf;
ALBASE_EFX_EXTERN_KW LPALEFFECTFV alEffectfv;
ALBASE_EFX_EXTERN_KW LPALGETEFFECTI alGetEffecti;
ALBASE_EFX_EXTERN_KW LPALGETEFFECTI alGetEffectiv;
ALBASE_EFX_EXTERN_KW LPALGETEFFECTF alGetEffectf;
ALBASE_EFX_EXTERN_KW LPALGETEFFECTFV alGetEffectfv;

ALBASE_EFX_EXTERN_KW LPALGENFILTERS alGenFilters;
ALBASE_EFX_EXTERN_KW LPALDELETEFILTERS alDeleteFilters;
ALBASE_EFX_EXTERN_KW LPALISFILTER alIsFilter;
ALBASE_EFX_EXTERN_KW LPALFILTERI alFilteri;
ALBASE_EFX_EXTERN_KW LPALFILTERIV alFilteriv;
ALBASE_EFX_EXTERN_KW LPALFILTERF alFilterf;
ALBASE_EFX_EXTERN_KW LPALFILTERFV alFilterfv;
ALBASE_EFX_EXTERN_KW LPALGETFILTERI alGetFilteri;
ALBASE_EFX_EXTERN_KW LPALGETFILTERIV alGetFilteriv;
ALBASE_EFX_EXTERN_KW LPALGETFILTERF alGetFilterf;
ALBASE_EFX_EXTERN_KW LPALGETFILTERFV alGetFilterfv;

ALBASE_EFX_EXTERN_KW LPALGENAUXILIARYEFFECTSLOTS alGenAuxiliaryEffectSlots;
ALBASE_EFX_EXTERN_KW LPALDELETEAUXILIARYEFFECTSLOTS alDeleteAuxiliaryEffectSlots;
ALBASE_EFX_EXTERN_KW LPALISAUXILIARYEFFECTSLOT alIsAuxiliaryEffectSlot;
ALBASE_EFX_EXTERN_KW LPALAUXILIARYEFFECTSLOTI alAuxiliaryEffectSloti;
ALBASE_EFX_EXTERN_KW LPALAUXILIARYEFFECTSLOTIV alAuxiliaryEffectSlotiv;
ALBASE_EFX_EXTERN_KW LPALAUXILIARYEFFECTSLOTF alAuxiliaryEffectSlotf;
ALBASE_EFX_EXTERN_KW LPALAUXILIARYEFFECTSLOTFV alAuxiliaryEffectSlotfv;

#undef ALBASE_EFX_EXTERN_KW

char albase_loadEFX(void);

#endif