file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS "base/*.h" "base/*.c")
add_library(effectbase OBJECT ${SOURCES})
unset(SOURCES)
target_link_libraries(effectbase PUBLIC alutil jsonutil)
set_target_properties(effectbase PROPERTIES POSITION_INDEPENDENT_CODE ON)

macro(defmod target source)
    add_library(${target} SHARED ${source})
    set_target_properties(${target} PROPERTIES PREFIX "")
    target_link_libraries(${target} PRIVATE effectbase alutil)
    target_defsym(${target} PRIVATE "dspmodule_cleanup" "alutil_quit")
endmacro()

defmod(dspeaxreverb "eaxreverb.c")
defmod(dspchorus "chorus.c")
#defmod(dspringmod "src/ringmod.c")
#defmod(dspflanger "src/flanger.c")