file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS "src/*.h" "src/*.c")
add_library(dspalbase OBJECT ${SOURCES})
unset(SOURCES)
target_link_libraries(dspalbase PUBLIC OpenAL::OpenAL)
set_target_properties(dspalbase PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_include_directories(dspalbase PUBLIC "include/")